"""Shared constants for scoring, keyword extraction, and UI copy."""

from __future__ import annotations

CORE_SECTION_ORDER = [
    "summary",
    "experience",
    "skills",
    "projects",
    "education",
    "certifications",
]

REQUIRED_SECTIONS = ["summary", "experience", "skills", "education"]

SECTION_PATTERNS = {
    "summary": [
        r"summary",
        r"professional summary",
        r"profile",
        r"career summary",
        r"about",
    ],
    "experience": [
        r"experience",
        r"work experience",
        r"professional experience",
        r"employment history",
        r"career history",
    ],
    "skills": [
        r"skills",
        r"technical skills",
        r"core skills",
        r"competencies",
        r"tools",
    ],
    "projects": [
        r"projects",
        r"selected projects",
        r"project experience",
        r"academic projects",
    ],
    "education": [
        r"education",
        r"academic background",
        r"qualifications",
    ],
    "certifications": [
        r"certifications",
        r"licenses",
        r"awards",
        r"certificates",
    ],
}

STOPWORDS = {
    "a",
    "about",
    "across",
    "after",
    "all",
    "an",
    "and",
    "any",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "between",
    "both",
    "build",
    "by",
    "can",
    "clear",
    "collaborate",
    "communication",
    "create",
    "data",
    "deliver",
    "demonstrated",
    "develop",
    "do",
    "driven",
    "during",
    "each",
    "ensure",
    "experience",
    "for",
    "from",
    "good",
    "have",
    "high",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "knowledge",
    "looking",
    "must",
    "of",
    "on",
    "or",
    "our",
    "preferred",
    "required",
    "responsibilities",
    "role",
    "should",
    "skills",
    "solid",
    "strong",
    "such",
    "team",
    "that",
    "the",
    "their",
    "them",
    "then",
    "this",
    "through",
    "to",
    "using",
    "we",
    "well",
    "will",
    "with",
    "work",
    "working",
    "you",
    "your",
    "years",
}

ACTION_VERBS = {
    "accelerated",
    "achieved",
    "analyzed",
    "architected",
    "automated",
    "built",
    "coordinated",
    "created",
    "delivered",
    "designed",
    "developed",
    "drove",
    "executed",
    "expanded",
    "generated",
    "implemented",
    "improved",
    "increased",
    "launched",
    "led",
    "managed",
    "modeled",
    "optimized",
    "owned",
    "reduced",
    "scaled",
    "shipped",
    "streamlined",
    "supported",
    "transformed",
}

WEAK_VERB_REPLACEMENTS = {
    "assisted": "Supported",
    "helped": "Supported",
    "participated in": "Contributed to",
    "responsible for": "Owned",
    "tasked with": "Delivered",
    "worked on": "Built",
    "worked with": "Partnered with",
}

SCORING_WEIGHTS = {
    "keyword_alignment": 35.0,
    "semantic_relevance": 25.0,
    "section_quality": 15.0,
    "ats_readiness": 15.0,
    "achievement_evidence": 10.0,
}

GENERIC_KEYWORD_PHRASES = {
    "cross functional",
    "fast paced",
    "problem solving",
    "written communication",
}

SKILL_TAXONOMY = {
    "Programming": [
        "python",
        "sql",
        "r",
        "java",
        "javascript",
        "typescript",
        "scala",
        "c++",
        "c#",
        "bash",
    ],
    "Data & ML": [
        "machine learning",
        "deep learning",
        "nlp",
        "computer vision",
        "data analysis",
        "data science",
        "statistics",
        "feature engineering",
        "a/b testing",
        "forecasting",
        "time series",
        "regression",
        "classification",
    ],
    "Analytics & BI": [
        "tableau",
        "power bi",
        "excel",
        "google analytics",
        "looker",
        "dashboards",
        "reporting",
        "business intelligence",
        "experimentation",
    ],
    "Cloud & DevOps": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "airflow",
        "spark",
        "databricks",
        "snowflake",
        "git",
        "ci/cd",
    ],
    "Product & Delivery": [
        "agile",
        "scrum",
        "stakeholder management",
        "roadmapping",
        "product analytics",
        "project management",
        "experimentation strategy",
    ],
}

SKILL_SYNONYMS = {
    "python": {"python", "python3", "pandas", "numpy"},
    "sql": {"sql", "postgresql", "mysql", "sqlite", "t-sql"},
    "r": {"r", "rstudio"},
    "java": {"java"},
    "javascript": {"javascript", "js"},
    "typescript": {"typescript", "ts"},
    "scala": {"scala"},
    "c++": {"c++"},
    "c#": {"c#", ".net"},
    "bash": {"bash", "shell scripting"},
    "machine learning": {"machine learning", "ml", "predictive modeling"},
    "deep learning": {"deep learning", "neural networks"},
    "nlp": {"nlp", "natural language processing", "text analytics"},
    "computer vision": {"computer vision"},
    "data analysis": {"data analysis", "analytics", "analytical"},
    "data science": {"data science"},
    "statistics": {"statistics", "statistical modeling"},
    "feature engineering": {"feature engineering"},
    "a/b testing": {"a/b testing", "ab testing", "split testing"},
    "forecasting": {"forecasting", "demand forecasting"},
    "time series": {"time series"},
    "regression": {"regression"},
    "classification": {"classification"},
    "tableau": {"tableau"},
    "power bi": {"power bi", "powerbi"},
    "excel": {"excel", "spreadsheets"},
    "google analytics": {"google analytics", "ga4"},
    "looker": {"looker", "looker studio"},
    "dashboards": {"dashboards", "dashboarding"},
    "reporting": {"reporting", "reports"},
    "business intelligence": {"business intelligence", "bi"},
    "experimentation": {"experimentation", "testing strategy"},
    "aws": {"aws", "amazon web services"},
    "azure": {"azure", "microsoft azure"},
    "gcp": {"gcp", "google cloud", "google cloud platform"},
    "docker": {"docker", "containerization"},
    "kubernetes": {"kubernetes", "k8s"},
    "terraform": {"terraform"},
    "airflow": {"airflow", "apache airflow"},
    "spark": {"spark", "apache spark", "pyspark"},
    "databricks": {"databricks"},
    "snowflake": {"snowflake"},
    "git": {"git", "github", "gitlab"},
    "ci/cd": {"ci/cd", "continuous integration", "continuous delivery"},
    "agile": {"agile"},
    "scrum": {"scrum"},
    "stakeholder management": {
        "stakeholder management",
        "stakeholder communication",
        "executive communication",
    },
    "roadmapping": {"roadmapping", "roadmap planning"},
    "product analytics": {"product analytics", "product analysis"},
    "project management": {"project management", "program management"},
    "experimentation strategy": {"experimentation strategy", "testing roadmap"},
}

SKILL_TO_CATEGORY = {
    skill: category for category, skills in SKILL_TAXONOMY.items() for skill in skills
}
